[package]
name = "{{project-name}}"
version = "0.1.0"
edition = "2021"

[profile.release]
opt-level = 'z'
codegen-units = 1
lto = true

[dependencies]
leptos = { version = "0.7", features = ["csr"] }
console_log = "1"
console_error_panic_hook = "0.1"
log = "0.4"
